Add API endpoint `/tokenize` to tokenize expression
Guppy-Team/LogicCalculator pull request #32
Opened 2024-03-31 18:20 UTC by k4ffy

closes #30

2024-04-02 16:06 UTC, MikeKondr99 requested changes

2024-04-02 16:06 UTC, MikeKondr99 commented on LogicCalculator.ASP/Controllers/ApiController.cs
> +                (x => Regex.Match(x, @"^\d+(\.\d*)?").Success ? Regex.Match(x, @"^\d+(\.\d*)?").Length : 0, x => new NumberToken(double.Parse(x))),
Жесть какая. Во первых много раз матч делаешь во вторых такой простой код можно было и написать.
Лучше даже вынести как функцию.

2024-04-02 16:06 UTC, MikeKondr99 commented on LogicCalculator.ASP/Controllers/ApiController.cs
> +                (x => Regex.Match(x, @"^\s+").Success ? Regex.Match(x, @"^\s+").Length : 0, x => new SpaceToken()),
искать сразу несколько пустых символов хорошая идея.

2024-04-02 21:50 UTC, k4ffy commented on LogicCalculator.ASP/Controllers/ApiController.cs
> +                (x => Regex.Match(x, @"^\d+(\.\d*)?").Success ? Regex.Match(x, @"^\d+(\.\d*)?").Length : 0, x => new NumberToken(double.Parse(x))),
Размышления и попытки меня привели вот к такому:
```csharp
public ApiController()
{
    _tokenizer = new Tokenizer(new (Func<string, int>, Func<string, IToken>)[]
    {
        (x => x.StartsWith("+") ? 1 : 0, x => new PlusToken()),
        (x => x.StartsWith("-") ? 1 : 0, x => new MinusToken()),
        (x => x.StartsWith("*") ? 1 : 0, x => new MultiplyToken()),
        (x => x.StartsWith("/") ? 1 : 0, x => new DivideToken()),
        (x => x.StartsWith("(") ? 1 : 0, x => new LeftBracketToken()),
        (x => x.StartsWith(")") ? 1 : 0, x => new RightBracketToken()),
        (x => x.StartsWith("=") ? 1 : 0, x => new EqualsToken()),

        (x => GetMatchLength(x, @"^\s+"), x => new SpaceToken()),
        (x => GetMatchLength(x, @"^\d+([,.]\d*)?"), x => new NumberToken(double.Parse(x)))
    });
}

private int GetMatchLength(string input, string pattern)
{
    var match = Regex.Match(input, pattern);
    return match.Success ? match.Length : 0;
}
```

Но появилась проблема с локалями. `double.Parse()` ожидает запятую, а на точку ошибку:
`System.FormatException: The input string '3.45' was not in a correct format.`

Есть вариант добавить в парсер дабла аргументы:
```csharp
double.Parse(x, NumberStyles.Number, CultureInfo.InvariantCulture))
```
но выглядит это, как мне кажется, не намного лучше того, что было

2024-04-03 16:13 UTC, MikeKondr99 commented on LogicCalculator.ASP/Controllers/ApiController.cs
> +                (x => Regex.Match(x, @"^\d+(\.\d*)?").Success ? Regex.Match(x, @"^\d+(\.\d*)?").Length : 0, x => new NumberToken(double.Parse(x))),
Я думал вообще об простом интеграционном алгоритме.

2024-04-03 16:15 UTC, MikeKondr99 approved these changes

2024-04-09 09:03 UTC, merged